// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeqfMWAHRg4la_-hIem-t62ZZol3LVnzc',
    appId: '1:698704441882:web:417f8b6f95039d3bfa17a3',
    messagingSenderId: '698704441882',
    projectId: 'kurs-55f5b',
    authDomain: 'kurs-55f5b.firebaseapp.com',
    storageBucket: 'kurs-55f5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN0F8Q9YpUjy1PkLYgRlyezJP0ir4pesk',
    appId: '1:698704441882:android:32d676c79ca7f11efa17a3',
    messagingSenderId: '698704441882',
    projectId: 'kurs-55f5b',
    storageBucket: 'kurs-55f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKDm9nJPyRRBAG6Ipk4FCdqEf4jlJ5Vs',
    appId: '1:698704441882:ios:318b52de96d1216dfa17a3',
    messagingSenderId: '698704441882',
    projectId: 'kurs-55f5b',
    storageBucket: 'kurs-55f5b.firebasestorage.app',
    iosBundleId: 'com.example.kurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKDm9nJPyRRBAG6Ipk4FCdqEf4jlJ5Vs',
    appId: '1:698704441882:ios:318b52de96d1216dfa17a3',
    messagingSenderId: '698704441882',
    projectId: 'kurs-55f5b',
    storageBucket: 'kurs-55f5b.firebasestorage.app',
    iosBundleId: 'com.example.kurs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeqfMWAHRg4la_-hIem-t62ZZol3LVnzc',
    appId: '1:698704441882:web:ac53a8fd2f9940c5fa17a3',
    messagingSenderId: '698704441882',
    projectId: 'kurs-55f5b',
    authDomain: 'kurs-55f5b.firebaseapp.com',
    storageBucket: 'kurs-55f5b.firebasestorage.app',
  );
}
